version: '2'
services:
  telegraf:
    image: appcelerator/telegraf:telegraf-1.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      OUTPUT_INFLUXDB_ENABLED: "true"
      INFLUXDB_URL: "http://influxdb:8086"
      INPUT_DOCKER_ENABLED: "true"
  influxdb:
    image: appcelerator/influxdb-amp:1.0.0
  kapacitor:
    image: appcelerator/kapacitor-amp
    build: .
  sut:
    image: appcelerator/sut
    build: ./sut
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
